// scripts/site.config.js
//
// Everything site-wide that is a value rather than markup. Change the domain,
// author, or analytics counter here; build.js and the generated pages pick it
// up on the next `npm run build`.

const path = require("path");

const ROOT = path.resolve(__dirname, "..");

module.exports = {
  ROOT,


  site: {
    // No trailing slash. Used for canonical + og:url, which must be absolute.
    url: "https://www.hxrsh.tech",
    name: "Harsh Singh",
    title: "Harsh Singh — AI Engineer",
    description:
      "Portfolio and writing of Harsh Singh, AI engineer in Mumbai. Agentic systems, ML pipelines, RAG, MLOps, and the harnesses that make LLMs useful.",
    author: "Harsh Singh",
    email: "harshsingh90220@gmail.com",
    locale: "en_IN",
    themeColor: "#8540f5",
    // 512x512 square image used for og:image when a post has no cover.
    defaultOgImage: "assets/images/logo.png",
  },

  social: {
    github: "https://github.com/AarnoStormborn",
    x: "https://x.com/TheGlobalMinima",
    linkedin: "https://www.linkedin.com/in/harsh-singh-4428241b4/",
  },

  nav: {
    // `hash` links point at index.html sections; pages outside index get the
    // index.html prefix so the browser can still resolve them.
    items: [
      { label: "About", href: "index.html#about", id: "about" },
      { label: "Experience", href: "index.html#experience", id: "experience" },
      { label: "Projects", href: "index.html#projects", id: "projects" },
      { label: "Contact", href: "index.html#contact", id: "contact" },
    ],
  },

  analytics: {
    // GoatCounter: free for non-commercial personal sites.
    // Sign up at https://www.goatcounter.com/ choosing this code, then the
    // snippet below starts reporting within a pageview or two.
    // Set enabled: false to omit the snippet entirely.
    enabled: true,
    code: "hxrsh",
    // Local dev should never pollute the counter.
    skipLocal: true,
  },

  blog: {
    manifest: "posts.json",
    outDir: "blogs", // posts land at blogs/<slug>/index.html
    // Posts are listed newest-first; anything older than this many days is
    // still rendered but flagged in build output as a nudge to refresh it.
    staleAfterDays: 240,
    rssItemCount: 20,
    feed: {
      title: "Harsh Singh — Writing",
      description: "Notes on AI engineering, agents, harnesses, and shipping ML systems.",
      file: "feed.xml",
    },
  },

  build: {
    // Committed + served: assets/js/blog.js fetches this at runtime so the
    // client-side fallback can render images with correct dimensions too.
    imageManifest: "assets/data/image-dims.json",
    // Generated pages carry this marker so nobody hand-edits a file that the
    // next `npm run build` would overwrite.
    marker: "<!-- GENERATED by scripts/build.js from {src} — do not edit -->",
  },
};
